#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GPS_Tracker_App.Resource", IsApplication=true)]

namespace GPS_Tracker_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int bluetooth = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int btnCenter = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int btnScan = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int btnSend = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int btnZoom = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int etSend = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int height = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int lstData = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int lstNew = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int lstPaired = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int map = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Bluetooth = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeviceList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Map = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int OptionsMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int NoNewDevice = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int NoPairedDevice = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
